---
driver:
  name: vagrant
  customize:
    memory: 1024
    cpus: 2
  synced_folders:
    - ["", "/tmp/build"]

provisioner:
  name: chef_solo

platforms:
  - name: centos-6.5
  - name: centos-6.5-i386
  - name: ubuntu-14.04
  - name: ubuntu-14.10-i386
  - name: centos-5.11
  - name: ubuntu-10.04
  - name: ubuntu-12.04

suites:
  - name: build
    excludes:
      - centos-6.5-i386
      - ubuntu-14.04
      - ubuntu-14.10-i386
      - centos-5.11
      - ubuntu-10.04
      - ubuntu-12.04
    run_list:
      - recipe[uchiwa-build]
    attributes:
      uchiwa-build:
        uchiwa_version: <%= ENV['UCHIWA_VERSION'] %>
        build_number: <%= ENV['BUILD_NUMBER'] %>
        uchiwa_revision: <%= ENV['UCHIWA_REVISION'] %>
  - name: test
    run_list:
      - recipe[uchiwa-build::test]
    attributes:
      uchiwa-build:
        uchiwa_version: <%= ENV['UCHIWA_VERSION'] %>
        build_number: <%= ENV['BUILD_NUMBER'] %>
        uchiwa_revision: <%= ENV['UCHIWA_REVISION'] %>
